### ISSUE TITLE
etcd.EtcdException: No more machines in the cluster

### ISSUE THREAD

**Issue by olalonde** [skrat/rabbitmq-etcd#2]
```bash
Aug 09 17:59:13 ec2.internal docker[20751]: * webmachine
Aug 09 18:03:14 ec2.internal docker[20751]: => Connecting to etcd at 10.21.21.1
Aug 09 18:03:14 ec2.internal docker[20751]: => Creating vhost somevhost
Aug 09 18:03:14 ec2.internal docker[20751]: => Creating user someuser:somepass with tags
Aug 09 18:03:14 ec2.internal docker[20751]: Traceback (most recent call last):
Aug 09 18:03:14 ec2.internal docker[20751]: File "/configsync.py", line 118, in <module>
Aug 09 18:03:14 ec2.internal docker[20751]: client.read(PREFIX, recursive=True, wait=True)
Aug 09 18:03:14 ec2.internal docker[20751]: File "/usr/lib/python2.7/site-packages/etcd/client.py", line 312, in read
Aug 09 18:03:14 ec2.internal docker[20751]: self.key_endpoint + key, self._MGET, params=params, timeout=timeout)
Aug 09 18:03:14 ec2.internal docker[20751]: File "/usr/lib/python2.7/site-packages/etcd/client.py", line 527, in api_execute
Aug 09 18:03:14 ec2.internal docker[20751]: self._base_uri = self._next_server()
Aug 09 18:03:14 ec2.internal docker[20751]: File "/usr/lib/python2.7/site-packages/etcd/client.py", line 485, in _next_server
Aug 09 18:03:14 ec2.internal docker[20751]: raise etcd.EtcdException('No more machines in the cluster')
Aug 09 18:03:14 ec2.internal docker[20751]: etcd.EtcdException: No more machines in the cluster
```

Getting this in logs... is that a bug or is it normal?

**Comment by olalonde** [comment]
Setting my user permissions in etcd seemed to fix the problem.
